// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type RegistrationForm struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type User struct {
	Username string `json:"username"`
	ID       string `json:"id"`
}
